#!/usr/bin/env bash

flag=true
c_dir="conversion-test"
#echo "Preparing amber input..."
# ${SPRANK_HOME}/bin/ambertools_prepare_rec -r ${c_dir}/rec/rec.pdb -o ${c_dir}/rec/amber
# ${SPRANK_HOME}/bin/ambertools_prepare_cpd -c ${c_dir}/cpd/cpd.sdf -o ${c_dir}/cpd/amber

for name in "rdock" "vina"; do
  echo "----------------------------------------------"
  echo "Running conversion test for ${name} poses..."
  echo "----------------------------------------------"

  rm -f ${c_dir}/pose/${name}_pose.mol2

  if [ ${name} == "rdock" ]; then
    ${SPRANK_HOME}/bin/convert_rdock_pose -r ${c_dir}/cpd/amber/cpd.amber.mol2 -p ${c_dir}/pose/rdock_pose.sd -o ${c_dir}/pose/rdock_pose.mol2
  else
    ${SPRANK_HOME}/bin/convert_vina_pose -r ${c_dir}/cpd/amber/cpd.amber.mol2 -p ${c_dir}/pose/vina_pose.pdbqt -o ${c_dir}/pose/vina_pose.mol2
  fi
  ${SPRANK_HOME}/bin/check_atom_order -c ${c_dir}/cpd/amber/cpd.amber.mol2 --c_mol2_type amber -p ${c_dir}/pose/${name}_pose.mol2 --p_mol2_type amber
  ${SPRANK_HOME}/bin/sprank -r ${c_dir}/rec/amber/rec.amber.mol2 -c ${c_dir}/cpd/amber/cpd.amber.mol2 -p ${c_dir}/pose/${name}_pose.mol2 &>${c_dir}/score/${name}_pose_score.dat
  ${SPRANK_HOME}/bin/sprank-rf -r ${c_dir}/rec/amber/rec.amber.mol2 -c ${c_dir}/cpd/amber/cpd.amber.mol2 -p ${c_dir}/pose/${name}_pose.mol2 -o ${c_dir}/score/${name}_pose_random_forest_score.dat

  echo "Checking sprank..."
  # compare the sprank predicted scores with reference
  diff ${c_dir}/score/${name}_pose_score.dat ${c_dir}/score/reference.${name}_pose_score.dat &>${c_dir}/score/${name}_pose_score.dat.diff
  if [ ! -s "${c_dir}/score/${name}_pose_score.dat.diff" ]; then
    echo "PASSED: ${name} conversion test."
    rm -f ${c_dir}/score/${name}_pose_score.dat.diff
  else
    echo "POSSIBLE FAILURE: ${name} conversion test. Please check ${c_dir}/score/${name}_pose_score.dat.diff"
    flag=false
  fi

  echo "Checking sprank-rf..."
  # compare the sprank-rf predicted scores with reference
  diff ${c_dir}/score/${name}_pose_random_forest_score.dat ${c_dir}/score/reference.${name}_pose_random_forest_score.dat &>${c_dir}/score/${name}_pose_random_forest_score.dat.diff
  if [ ! -s "${c_dir}/score/${name}_pose_random_forest_score.dat.diff" ]; then
    echo "PASSED: ${name} converstion test."
    rm -f ${c_dir}/score/${name}_pose_random_forest_score.dat.diff
  else
    echo "POSSIBLE FAILURE: ${name} conversion test. Please check ${c_dir}/score/${name}_pose_random_forest_score.dat.diff"
    flag=false
  fi
done

if [ "${flag}" = false ]; then
  echo "FAILED!"
else
  echo "SUCCEEDED!"
fi
